=== Conchsk/Materials-Data-Specification/sic-ceramic-coating/sic-ceramic-coating-calc.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <!-- refer basic xsds -->
  <xsd:include schemaLocation="../file.xsd" />
  <xsd:include schemaLocation="../info.xsd" />
  <xsd:include schemaLocation="../unit.xsd" />
  <!-- main xsd -->
  <xsd:element name="SIC-ceramic-coating-calc">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="information">
          <xsd:complexType>
            <xsd:complexContent>
              <xsd:extension base="info">
                <xsd:sequence>
                  <xsd:element name="chemical-formula" type="xsd:string" />
                  <xsd:element name="name" type="xsd:string" />
                  <xsd:element name="number" type="xsd:string" />
                  <xsd:element name="calculation-method" type="xsd:string" />
                  <xsd:element name="calculation-software" type="xsd:string" />
                </xsd:sequence>
              </xsd:extension>
            </xsd:complexContent>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="structure" minOccurs="0">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="crystal-structure" type="file-list" minOccurs="0" />
              <xsd:element name="lattice-parameter" minOccurs="0">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="a" type="angstrom" minOccurs="0" />
                    <xsd:element name="b" type="angstrom" minOccurs="0" />
                    <xsd:element name="c" type="angstrom" minOccurs="0" />
                    <xsd:element name="alpha" type="degrees" minOccurs="0" />
                    <xsd:element name="beta" type="degrees" minOccurs="0" />
                    <xsd:element name="gamma" type="degrees" minOccurs="0" />
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="bond-lengths" minOccurs="0">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="bond-lengths-record" maxOccurs="unbounded">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="bond" type="xsd:string" />
                          <xsd:element name="length" type="angstrom" />
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="bond-angles" minOccurs="0">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="bond-angles-record" maxOccurs="unbounded">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="bond" type="xsd:string" />
                          <xsd:element name="angle" type="degrees" />
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="fermi-energy" type="file-list" minOccurs="0" />
              <xsd:element name="partial-density-of-states" type="file-list" minOccurs="0" />
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="elastic-constants" minOccurs="0">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="elastic-constants-records" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="elastic-constant" type="xsd:string" />
                    <xsd:element name="value" type="gigapascal" />
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="mechanical-properties" minOccurs="0">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="bulk-modulus" type="gigapascal" minOccurs="0" />
              <xsd:element name="shear-modulus" type="gigapascal" minOccurs="0" />
              <xsd:element name="youngs-modulus" type="gigapascal" minOccurs="0" />
              <xsd:element name="poissons-ratio" type="gigapascal" minOccurs="0" />
              <xsd:element name="zener-anisotroy-ratio" type="gigapascal" minOccurs="0" />
              <xsd:element name="anisotropic-youngs-modulus" type="file-list" minOccurs="0" />
              <xsd:element name="maximum-youngs-modulus" minOccurs="0">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value" type="gigapascal" />
                    <xsd:element name="direction" type="xsd:string" />
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="minimum-youngs-modulus" minOccurs="0">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value" type="gigapascal" />
                    <xsd:element name="direction" type="xsd:string" />
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="structural-stability" minOccurs="0">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="changes-in-the-x-coordinate-versus-pressures" minOccurs="0">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="table" minOccurs="0">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="table-record" maxOccurs="unbounded">
                            <xsd:complexType>
                              <xsd:sequence>
                                <xsd:element name="pressure" type="gigapascal" />
                                <xsd:element name="x-coordinate" type="xsd:float" />
                              </xsd:sequence>
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="attachment" type="file-list" minOccurs="0" />
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="bond-length-at-various-pressures" minOccurs="0">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="table" minOccurs="0">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="table-record" maxOccurs="unbounded">
                            <xsd:complexType>
                              <xsd:sequence>
                                <xsd:element name="pressure" type="gigapascal" />
                                <xsd:element name="bond" type="xsd:string" />
                                <xsd:element name="bond-length" type="angstrom" />
                              </xsd:sequence>
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="attachment" type="file-list" minOccurs="0" />
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="elastic-stiffness-at-high-pressures" minOccurs="0">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="pressure-dependent-elastic-constants" minOccurs="0">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="table" minOccurs="0">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="table-record" maxOccurs="unbounded">
                            <xsd:complexType>
                              <xsd:sequence>
                                <xsd:element name="pressure" type="gigapascal" />
                                <xsd:element name="C11" type="gigapascal" />
                                <xsd:element name="C12" type="gigapascal" />
                                <xsd:element name="C44" type="gigapascal" />
                              </xsd:sequence>
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="attachment" type="file-list" minOccurs="0" />
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="mechanical-properties-at-high-pressures" minOccurs="0">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="pressure-dependent-mechanical-properties" minOccurs="0">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="table" minOccurs="0">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="table-record" maxOccurs="unbounded">
                            <xsd:complexType>
                              <xsd:sequence>
                                <xsd:element name="pressure" type="gigapascal" />
                                <xsd:element name="bulk-modulus" type="gigapascal" />
                                <xsd:element name="shear-modulus" type="gigapascal" />
                                <xsd:element name="youngs-modulus" type="gigapascal" />
                              </xsd:sequence>
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="attachment" type="file-list" minOccurs="0" />
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="thermal-properties" minOccurs="0">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="shear-sound-velocity" minOccurs="0">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value" type="xsd:float" />
                    <xsd:element name="unit" type="xsd:string" fixed="cm/s" />
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="longitudinal-sound-velocity" minOccurs="0">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value" type="xsd:float" />
                    <xsd:element name="unit" type="xsd:string" fixed="cm/s" />
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="average-sound-velocity" minOccurs="0">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value" type="xsd:float" />
                    <xsd:element name="unit" type="xsd:string" fixed="cm/s" />
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="the-minimum-thermal-conductivity" minOccurs="0">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="value" type="xsd:float" />
                    <xsd:element name="unit" type="xsd:string" fixed="W/(m·K)" />
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== Conchsk/Materials-Data-Specification/sic-ceramic-coating/sic-ceramic-coating-calc.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="sic-ceramic-coating-calc.xsl"?>
<SIC-ceramic-coating-calc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sic-ceramic-coating-calc.xsd">
  <information>
    <data-source>上硅所</data-source>
    <upload-date>2018-09-28</upload-date>
    <doi>**</doi>
    <chemical-formula>La_2Ce_2O_7</chemical-formula>
    <name>####</name>
    <number>####</number>
    <calculation-method>First-principles calculations</calculation-method>
    <calculation-software>####</calculation-software>
  </information>
  <structure>
    <crystal-structure>
      <file>
        <name>cs.jpg</name>
        <url>cs.jpg</url>
      </file>
    </crystal-structure>
    <lattice-parameter>
      <a>
        <value>1</value>
        <unit>Å</unit>
      </a>
      <b>
        <value>1</value>
        <unit>Å</unit>
      </b>
      <c>
        <value>1</value>
        <unit>Å</unit>
      </c>
      <alpha>
        <value>90</value>
        <unit>°</unit>
      </alpha>
      <beta>
        <value>90</value>
        <unit>°</unit>
      </beta>
      <gamma>
        <value>90</value>
        <unit>°</unit>
      </gamma>
    </lattice-parameter>
    <bond-lengths>
      <bond-lengths-record>
        <bond>La-O(8a)</bond>
        <length>
          <value>2.21</value>
          <unit>Å</unit>
        </length>
      </bond-lengths-record>
      <bond-lengths-record>
        <bond>La-O(48f)</bond>
        <length>
          <value>2.58</value>
          <unit>Å</unit>
        </length>
      </bond-lengths-record>
    </bond-lengths>
    <bond-angles>
      <bond-angles-record>
        <bond>B-O-B</bond>
        <angle>
          <value>137</value>
          <unit>°</unit>
        </angle>
      </bond-angles-record>
    </bond-angles>
    <fermi-energy>
      <file>
        <name>fe.jpg</name>
        <url>fe.jpg</url>
      </file>
    </fermi-energy>
    <partial-density-of-states>
      <file>
        <name>La.jpg</name>
        <url>La.jpg</url>
      </file>
      <file>
        <name>Ce.jpg</name>
        <url>Ce.jpg</url>
      </file>
      <file>
        <name>O.jpg</name>
        <url>O.jpg</url>
      </file>
    </partial-density-of-states>
  </structure>
  <elastic-constants>
    <elastic-constants-records>
      <elastic-constant>C_{11}</elastic-constant>
      <value>
        <value>315</value>
        <unit>GPa</unit>
      </value>
    </elastic-constants-records>
    <elastic-constants-records>
      <elastic-constant>C_{12}</elastic-constant>
      <value>
        <value>143</value>
        <unit>GPa</unit>
      </value>
    </elastic-constants-records>
    <elastic-constants-records>
      <elastic-constant>C_{44}</elastic-constant>
      <value>
        <value>111</value>
        <unit>GPa</unit>
      </value>
    </elastic-constants-records>
  </elastic-constants>
  <mechanical-properties>
    <bulk-modulus>
      <value>200</value>
      <unit>GPa</unit>
    </bulk-modulus>
    <shear-modulus>
      <value>100</value>
      <unit>GPa</unit>
    </shear-modulus>
    <youngs-modulus>
      <value>258</value>
      <unit>GPa</unit>
    </youngs-modulus>
    <poissons-ratio>
      <value>0.29</value>
      <unit>GPa</unit>
    </poissons-ratio>
    <zener-anisotroy-ratio>
      <value>1.29</value>
      <unit>GPa</unit>
    </zener-anisotroy-ratio>
    <anisotropic-youngs-modulus>
      <file>
        <name>aym.jpg</name>
        <url>aym.jpg</url>
      </file>
    </anisotropic-youngs-modulus>
    <maximum-youngs-modulus>
      <value>
        <value>281</value>
        <unit>GPa</unit>
      </value>
      <direction>[1 1 1]</direction>
    </maximum-youngs-modulus>
    <minimum-youngs-modulus>
      <value>
        <value>214</value>
        <unit>GPa</unit>
      </value>
      <direction>[1 0 0]</direction>
    </minimum-youngs-modulus>
  </mechanical-properties>
  <structural-stability>
    <changes-in-the-x-coordinate-versus-pressures>
      <table>
        <table-record>
          <pressure>
            <value>0</value>
            <unit>GPa</unit>
          </pressure>
          <x-coordinate>0.35</x-coordinate>
        </table-record>
      </table>
      <attachment>
        <file>
          <name>x-p.jpg</name>
          <url>x-p.jpg</url>
        </file>
      </attachment>
    </changes-in-the-x-coordinate-versus-pressures>
    <bond-length-at-various-pressures>
      <table>
        <table-record>
          <pressure>
            <value>0</value>
            <unit>GPa</unit>
          </pressure>
          <bond>Ge-O2</bond>
          <bond-length>
            <value>1</value>
            <unit>Å</unit>
          </bond-length>
        </table-record>
        <table-record>
          <pressure>
            <value>0</value>
            <unit>GPa</unit>
          </pressure>
          <bond>La-O1</bond>
          <bond-length>
            <value>1</value>
            <unit>Å</unit>
          </bond-length>
        </table-record>
        <table-record>
          <pressure>
            <value>10</value>
            <unit>GPa</unit>
          </pressure>
          <bond>Ge-O2</bond>
          <bond-length>
            <value>1</value>
            <unit>Å</unit>
          </bond-length>
        </table-record>
      </table>
      <attachment>
        <file>
          <name>bl-p.jpg</name>
          <url>bl-p.jpg</url>
        </file>
      </attachment>
    </bond-length-at-various-pressures>
  </structural-stability>
  <elastic-stiffness-at-high-pressures>
    <pressure-dependent-elastic-constants>
      <table>
        <table-record>
          <pressure>
            <value>0</value>
            <unit>GPa</unit>
          </pressure>
          <C11>
            <value>1</value>
            <unit>GPa</unit>
          </C11>
          <C12>
            <value>1</value>
            <unit>GPa</unit>
          </C12>
          <C44>
            <value>1</value>
            <unit>GPa</unit>
          </C44>
        </table-record>
        <table-record>
          <pressure>
            <value>10</value>
            <unit>GPa</unit>
          </pressure>
          <C11>
            <value>1</value>
            <unit>GPa</unit>
          </C11>
          <C12>
            <value>1</value>
            <unit>GPa</unit>
          </C12>
          <C44>
            <value>1</value>
            <unit>GPa</unit>
          </C44>
        </table-record>
      </table>
      <attachment>
        <file>
          <name>ec-p.jpg</name>
          <url>ec-p.jpg</url>
        </file>
      </attachment>
    </pressure-dependent-elastic-constants>
  </elastic-stiffness-at-high-pressures>
  <mechanical-properties-at-high-pressures>
    <pressure-dependent-mechanical-properties>
      <table>
        <table-record>
          <pressure>
            <value>0</value>
            <unit>GPa</unit>
          </pressure>
          <bulk-modulus>
            <value>1</value>
            <unit>GPa</unit>
          </bulk-modulus>
          <shear-modulus>
            <value>1</value>
            <unit>GPa</unit>
          </shear-modulus>
          <youngs-modulus>
            <value>1</value>
            <unit>GPa</unit>
          </youngs-modulus>
        </table-record>
        <table-record>
          <pressure>
            <value>10</value>
            <unit>GPa</unit>
          </pressure>
          <bulk-modulus>
            <value>1</value>
            <unit>GPa</unit>
          </bulk-modulus>
          <shear-modulus>
            <value>1</value>
            <unit>GPa</unit>
          </shear-modulus>
          <youngs-modulus>
            <value>1</value>
            <unit>GPa</unit>
          </youngs-modulus>
        </table-record>
      </table>
      <attachment>
        <file>
          <name>m-p.jpg</name>
          <url>m-p.jpg</url>
        </file>
      </attachment>
    </pressure-dependent-mechanical-properties>
  </mechanical-properties-at-high-pressures>
  <thermal-properties>
    <shear-sound-velocity>
      <value>3.85e5</value>
      <unit>cm/s</unit>
    </shear-sound-velocity>
    <longitudinal-sound-velocity>
      <value>7.05e5</value>
      <unit>cm/s</unit>
    </longitudinal-sound-velocity>
    <average-sound-velocity>
      <value>4.30e5</value>
      <unit>cm/s</unit>
    </average-sound-velocity>
    <the-minimum-thermal-conductivity>
      <value>1.14</value>
      <unit>W/(m·K)</unit>
    </the-minimum-thermal-conductivity>
  </thermal-properties>
</SIC-ceramic-coating-calc>
